name: CI
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
  upload_artifacts:
    name: Upload Artifacts
    needs: [ create_release ]
    runs-on: ubuntu-latest
    steps:
      - name: Upload APK to Release
        uses: skx/github-action-publish-binaries@release-1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create_release.outputs.id }}
          args: app/build/outputs/apk/release/**.apk

